#!/usr/bin/env python3
"""Patch the generated voxsv main.c with voxsv-specific helper code."""

from __future__ import annotations

import sys
from pathlib import Path

INPUT_LINE = "static const uint32_t input_0[] = SAMPLE_INPUT_0;\n"
ML_DATA_LINE = "static int32_t ml_data[CNN_NUM_OUTPUTS];\n"
UNLOAD_LINE = "  cnn_unload((uint32_t *) ml_data);\n"

PREPROCESS_BLOCK = """static const uint32_t input_0[] = SAMPLE_INPUT_0;

/*
 * Pre-processing guide for a live microphone pipeline:
 * 1. Capture mono PCM with the same sample rate used during training.
 * 2. Apply the same framing/windowing pipeline used to build VoxCeleb2_SV features.
 * 3. Convert audio to an 80-bin x 128-frame log-mel/filterbank tensor.
 * 4. Apply the same normalization and int8 quantization used during training.
 * 5. Pack the final tensor as CHW 1x80x128 and copy 2560 words into 0x50400000.
 * 6. Replace the SAMPLE_INPUT memcpy below with your computed feature buffer.
 *
 * Notes:
 * - This network expects acoustic features, not raw microphone PCM samples.
 * - Quantization/range mismatches will hurt accuracy even if the CNN runs.
 * - After inference, compare the normalized 64-D embedding with enrolled
 *   speaker embeddings using cosine similarity or dot product.
 */
"""

ML_DATA_BLOCK = """#define VOXSV_EMBEDDING_DIM 64

static int32_t ml_data[CNN_NUM_OUTPUTS];
static int8_t voxsv_embedding_q7[VOXSV_EMBEDDING_DIM];

static float voxsv_sqrt(float value)
{
  float x = value;
  int i;

  if (value <= 0.0f)
    return 0.0f;

  if (x < 1.0f)
    x = 1.0f;

  for (i = 0; i < 8; i++)
    x = 0.5f * (x + value / x);

  return x;
}

static int8_t voxsv_clamp_q7(float value)
{
  if (value > 127.0f)
    return 127;
  if (value < -128.0f)
    return -128;
  return (int8_t) (value >= 0.0f ? value + 0.5f : value - 0.5f);
}

static void voxsv_normalize_embedding_q7(const int32_t *packed_src, int8_t *dst)
{
  const int16_t *src = (const int16_t *) packed_src;
  float sum = 0.0f;
  float scale;
  int i;

  for (i = 0; i < VOXSV_EMBEDDING_DIM; i++)
    sum += (float) src[i] * (float) src[i];

  if (sum <= 0.0f) {
    memset(dst, 0, VOXSV_EMBEDDING_DIM);
    return;
  }

  scale = 128.0f / voxsv_sqrt(sum);

  for (i = 0; i < VOXSV_EMBEDDING_DIM; i++)
    dst[i] = voxsv_clamp_q7((float) src[i] * scale);
}
"""

UNLOAD_BLOCK = """  cnn_unload((uint32_t *) ml_data);
  voxsv_normalize_embedding_q7(ml_data, voxsv_embedding_q7);
  printf("Normalized embedding stored in voxsv_embedding_q7 (Q7, 64 dims).\\n");
"""

# Anchor: the standard single-shot inference block generated by ai8xize.
# After the previous patches (UNLOAD_BLOCK), this section has the KAT check
# and shutdown. We replace it with a #ifdef VOXSV_UART_MODE conditional that
# either runs a UART streaming loop (for EER evaluation) or the KAT test.
INFERENCE_ANCHOR = (
    "  cnn_init(); // Bring state machine into consistent state\n"
    "  cnn_load_weights(); // Load kernels\n"
    "  cnn_load_bias();\n"
    "  cnn_configure(); // Configure state machine\n"
    "  load_input(); // Load data input\n"
    "  cnn_start(); // Start CNN processing\n"
    "\n"
    "  while (cnn_time == 0)\n"
    "    MXC_LP_EnterSleepMode(); // Wait for CNN\n"
    "\n"
    "  if (check_output() != CNN_OK) fail();\n"
    "  cnn_unload((uint32_t *) ml_data);\n"
    "  voxsv_normalize_embedding_q7(ml_data, voxsv_embedding_q7);\n"
    '  printf("Normalized embedding stored in voxsv_embedding_q7 (Q7, 64 dims).\\n");\n'
    "\n"
    '  printf("\\n*** PASS ***\\n\\n");\n'
    "\n"
    "#ifdef CNN_INFERENCE_TIMER\n"
    '  printf("Approximate inference time: %u us\\n\\n", cnn_time);\n'
    "#endif\n"
    "\n"
    "  cnn_disable(); // Shut down CNN clock, disable peripheral\n"
    "\n"
    "\n"
    "  return 0;\n"
    "}"
)

INFERENCE_UART_BLOCK = """\
  cnn_init(); // Bring state machine into consistent state
  cnn_load_weights(); // Load kernels
  cnn_load_bias();

#ifdef VOXSV_UART_MODE
  /* ------------------------------------------------------------------ *
   * UART streaming mode: host sends feature frames, board returns       *
   * 64-D embeddings.  Protocol (little-endian):                        *
   *   Boot   -> "VOXSV READY 10240 64\\n"                               *
   *   INP0 + 10240 B  -> EMB0 + u32 time_us + 64 x int8  (Q7 norm)    *
   *   INP1 + 10240 B  -> RAW0 + u32 time_us + 128 B (64 x int16 raw)  *
   * ------------------------------------------------------------------ */
  {
    mxc_uart_regs_t *uart = MXC_UART_GET_UART(CONSOLE_UART);
    volatile uint8_t *input_mem = (volatile uint8_t *)0x50400000;
    uint8_t tag[4];
    int i, c;

    printf("VOXSV READY 10240 64\\n");

    for (;;) {
      /* Read 4-byte command tag */
      for (i = 0; i < 4; i++) {
        do { c = MXC_UART_ReadCharacterRaw(uart); } while (c < 0);
        tag[i] = (uint8_t)c;
      }

      /* Read 10240-byte feature frame directly into CNN data SRAM */
      for (i = 0; i < 10240; i++) {
        do { c = MXC_UART_ReadCharacterRaw(uart); } while (c < 0);
        input_mem[i] = (uint8_t)c;
      }

      /* Run inference */
      cnn_time = 0;
      cnn_configure();
      cnn_start();
      while (cnn_time == 0)
        MXC_LP_EnterSleepMode();

      cnn_unload((uint32_t *)ml_data);

      /* Build and send 8-byte response header (tag + LE u32 time_us) */
      {
        uint32_t t = cnn_time;
        uint8_t hdr[8];
        hdr[4] = (uint8_t)(t);
        hdr[5] = (uint8_t)(t >> 8);
        hdr[6] = (uint8_t)(t >> 16);
        hdr[7] = (uint8_t)(t >> 24);

        if (tag[3] == '1') {
          /* INP1 -> RAW0: 64 x int16 raw embedding (128 bytes) */
          const uint8_t *raw = (const uint8_t *)ml_data;
          memcpy(hdr, "RAW0", 4);
          for (i = 0; i < 8; i++) { while (MXC_UART_WriteCharacterRaw(uart, hdr[i]) != E_SUCCESS); }
          for (i = 0; i < VOXSV_EMBEDDING_DIM * 2; i++) { while (MXC_UART_WriteCharacterRaw(uart, raw[i]) != E_SUCCESS); }
        } else {
          /* INP0 -> EMB0: 64 x int8 L2-normalised Q7 embedding */
          voxsv_normalize_embedding_q7(ml_data, voxsv_embedding_q7);
          memcpy(hdr, "EMB0", 4);
          for (i = 0; i < 8; i++) { while (MXC_UART_WriteCharacterRaw(uart, hdr[i]) != E_SUCCESS); }
          for (i = 0; i < VOXSV_EMBEDDING_DIM; i++) { while (MXC_UART_WriteCharacterRaw(uart, (uint8_t)voxsv_embedding_q7[i]) != E_SUCCESS); }
        }
      }
    }
  }
#else
  cnn_configure(); // Configure state machine
  load_input(); // Load data input
  cnn_start(); // Start CNN processing

  while (cnn_time == 0)
    MXC_LP_EnterSleepMode(); // Wait for CNN

  if (check_output() != CNN_OK) fail();
  cnn_unload((uint32_t *) ml_data);
  voxsv_normalize_embedding_q7(ml_data, voxsv_embedding_q7);
  printf("Normalized embedding stored in voxsv_embedding_q7 (Q7, 64 dims).\\n");

  printf("\\n*** PASS ***\\n\\n");

#ifdef CNN_INFERENCE_TIMER
  printf("Approximate inference time: %u us\\n\\n", cnn_time);
#endif

  cnn_disable(); // Shut down CNN clock, disable peripheral
#endif // VOXSV_UART_MODE

  return 0;
}"""


def patch_main(path: Path) -> bool:
    text = path.read_text(encoding="utf-8")
    changed = False

    if "Pre-processing guide for a live microphone pipeline:" not in text:
        if INPUT_LINE not in text:
            raise RuntimeError(f"Could not find input anchor in {path}")
        text = text.replace(INPUT_LINE, PREPROCESS_BLOCK, 1)
        changed = True

    if "voxsv_normalize_embedding_q7" not in text:
        if ML_DATA_LINE not in text:
            raise RuntimeError(f"Could not find ml_data anchor in {path}")
        if UNLOAD_LINE not in text:
            raise RuntimeError(f"Could not find cnn_unload anchor in {path}")

        text = text.replace(ML_DATA_LINE, ML_DATA_BLOCK, 1)
        text = text.replace(UNLOAD_LINE, UNLOAD_BLOCK, 1)
        changed = True

    if "VOXSV_UART_MODE" not in text:
        if INFERENCE_ANCHOR not in text:
            raise RuntimeError(f"Could not find inference anchor in {path}")
        text = text.replace(INFERENCE_ANCHOR, INFERENCE_UART_BLOCK, 1)
        changed = True

    if not changed:
        return False

    path.write_text(text, encoding="utf-8")
    return True


def main() -> int:
    if len(sys.argv) != 2:
        print("Usage: patch_voxsv_main.py <path-to-main.c>", file=sys.stderr)
        return 2

    path = Path(sys.argv[1])
    if not path.is_file():
        print(f"File not found: {path}", file=sys.stderr)
        return 1

    changed = patch_main(path)
    print(f"{'Patched' if changed else 'Already patched'} {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
