#!/usr/bin/env python3
"""
db_gen/manage_db.py — Speaker DB manager for VoxSV demo.

Loads the existing include/speaker_db.h so you can add or delete
speakers without re-recording everyone from scratch.

Usage
-----
  python db_gen/manage_db.py [--port /dev/ttyACM0]

To add a speaker the board must be in DB BUILD mode:
  1. make flash
  2. Hold SW1 within 3 s of "[INIT] Done."
"""

import serial
import serial.tools.list_ports
import numpy as np
import os
import re
import sys
import argparse
import time

SCRIPT_DIR    = os.path.dirname(os.path.abspath(__file__))
HEADER_PATH   = os.path.abspath(os.path.join(SCRIPT_DIR, '..', 'include', 'speaker_db.h'))
EMBEDDING_DIM = 64
Q7_NORM       = 128.0
PEAK_OK       = 1000
PEAK_MIN      = 300


# ── Header parse / write ──────────────────────────────────────────────────────

def load_header(path):
    """Parse speaker_db.h → list of (name, np.int8[64]). Returns [] if empty."""
    if not os.path.exists(path):
        return []
    with open(path) as f:
        content = f.read()

    m = re.search(r'#define\s+DB_NUM_ENTRIES\s+(\d+)', content)
    if not m or int(m.group(1)) == 0:
        return []

    m_names = re.search(r'#define\s+DB_SPEAKER_NAMES\s*\{([^}]+)\}', content)
    if not m_names:
        return []
    names = re.findall(r'"([^"]+)"', m_names.group(1))

    m_embs = re.search(r'#define\s+DB_EMBEDDINGS\s*\{(.+?)\n\}', content, re.DOTALL)
    if not m_embs:
        return []
    emb_block = m_embs.group(1).replace('\\\n', ' ')
    inner_blocks = re.findall(r'\{([^}]+)\}', emb_block)

    entries = []
    for name, block in zip(names, inner_blocks):
        try:
            vals = [int(v.strip()) for v in block.split(',') if v.strip()]
            if len(vals) == EMBEDDING_DIM:
                entries.append((name, np.array(vals, dtype=np.int8)))
        except ValueError:
            pass
    return entries


def write_header(entries, path):
    n = len(entries)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write('/* Auto-generated by db_gen/manage_db.py — do not edit */\n\n')
        f.write(f'#define DB_NUM_ENTRIES   {n}\n')
        f.write(f'#define DB_EMBEDDING_DIM {EMBEDDING_DIM}\n\n')
        if n == 0:
            f.write('#define DB_SPEAKER_NAMES {}\n\n')
            f.write('#define DB_EMBEDDINGS {}\n')
            return
        names_str = ', '.join(f'"{name[:6]}"' for name, _ in entries)
        f.write(f'#define DB_SPEAKER_NAMES {{ {names_str} }}\n\n')
        f.write('#define DB_EMBEDDINGS { \\\n')
        rows = [f'  /* {name[:6]:<6} */ {{ {", ".join(str(int(v)) for v in emb)} }}'
                for name, emb in entries]
        f.write(', \\\n'.join(rows))
        f.write(' \\\n}\n')
    print(f'  [saved] {n} speaker(s) → {os.path.relpath(path)}')


# ── Serial ────────────────────────────────────────────────────────────────────

def find_port():
    for p in serial.tools.list_ports.comports():
        desc = ((p.description or '') + (p.manufacturer or '')).lower()
        if any(k in desc for k in ('max32', 'ftdi', 'cp210', 'ch340', 'cmsis')):
            return p.device
    ports = list(serial.tools.list_ports.comports())
    return ports[0].device if ports else None


def open_serial(port, baud):
    try:
        ser = serial.Serial(port, baud, timeout=1)
        time.sleep(0.3)
        ser.reset_input_buffer()
        return ser
    except serial.SerialException as e:
        print(f'  Serial error: {e}')
        return None


def recv_one(ser, timeout=30):
    """Send GO to board, wait for READY → LEVEL → EMBED. Returns (emb, peak, rms)."""
    ser.write(b'G')   # trigger one recording cycle on the board
    buf = b''
    deadline = time.time() + timeout
    while time.time() < deadline:
        buf += ser.read(256)
        while b'\n' in buf:
            line, buf = buf.split(b'\n', 1)
            text = line.decode(errors='ignore').strip()
            if text == 'READY':
                return _recv_embed(ser, buf)
    return None, 0, 0


def _recv_embed(ser, leftover, timeout=30):
    buf, peak, rms = leftover, 0, 0
    deadline = time.time() + timeout
    while time.time() < deadline:
        buf += ser.read(256)
        while b'\n' in buf:
            line, buf = buf.split(b'\n', 1)
            text = line.decode(errors='ignore').strip()
            if text.startswith('LEVEL'):
                try:
                    peak = int(text.split('peak=')[1].split()[0])
                    rms  = int(text.split('rms=')[1].split()[0])
                except (IndexError, ValueError):
                    pass
            elif text.startswith('EMBED:'):
                try:
                    vals = [int(v) for v in text[6:].split(',')]
                    if len(vals) == EMBEDDING_DIM:
                        return np.array(vals, dtype=np.int8), peak, rms
                except ValueError:
                    pass
    return None, peak, rms


# ── Embedding math ────────────────────────────────────────────────────────────

def average_embeddings(emb_list):
    arr  = np.stack([e.astype(np.float32) for e in emb_list], axis=0)
    avg  = arr.mean(axis=0)
    norm = np.linalg.norm(avg)
    if norm > 1e-9:
        avg /= norm
    return np.clip(np.round(avg * Q7_NORM), -128, 127).astype(np.int8)


# ── Commands ──────────────────────────────────────────────────────────────────

def print_db(entries):
    if not entries:
        print('  (empty)')
    else:
        for i, (name, _) in enumerate(entries):
            print(f'  [{i}] {name}')


def cmd_add(entries, ser):
    if ser is None:
        print('  No serial connection — board required for recording.')
        return entries

    speaker = input('  New speaker name: ').strip()
    if not speaker:
        return entries
    if any(n == speaker for n, _ in entries):
        print(f'  "{speaker}" already exists. Delete it first.')
        return entries

    n_str = input(f'  Utterances for "{speaker}" [3]: ').strip()
    n_utt = int(n_str) if n_str.isdigit() and int(n_str) > 0 else 3

    print(f'\n  Recording {n_utt} utterance(s) — wait for green LED, then speak\n')

    embeddings, i = [], 0
    while i < n_utt:
        print(f'  [{i+1}/{n_utt}] Waiting for board...')
        emb, peak, rms = recv_one(ser)

        if emb is None:
            print(f'  [{i+1}/{n_utt}] TIMEOUT — retrying')
            continue

        quality = ('OK' if peak >= PEAK_OK else
                   'QUIET — speak louder' if peak >= 500 else
                   'TOO QUIET')
        print(f'  [{i+1}/{n_utt}] peak={peak:<5d} rms={rms:<5d}  {quality}')

        if peak < PEAK_MIN:
            print(f'  [{i+1}/{n_utt}] Discarded, retrying')
            continue

        embeddings.append(emb)
        i += 1

    if not embeddings:
        print('  No valid recordings — speaker not added.')
        return entries

    new_entries = entries + [(speaker, average_embeddings(embeddings))]
    print(f'  Added "{speaker}" ({len(embeddings)} utterance(s) averaged)')
    return new_entries


def cmd_delete(entries):
    if not entries:
        print('  DB is empty.')
        return entries
    print_db(entries)
    sel = input('  Index to delete (Enter to cancel): ').strip()
    if not sel.isdigit() or int(sel) >= len(entries):
        print('  Cancelled.')
        return entries
    name = entries[int(sel)][0]
    new_entries = [e for i, e in enumerate(entries) if i != int(sel)]
    print(f'  Deleted "{name}"')
    return new_entries


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser(description='VoxSV speaker DB manager')
    ap.add_argument('--port', default=None, help='Serial port (e.g. /dev/ttyACM0)')
    ap.add_argument('--baud', type=int, default=115200)
    args = ap.parse_args()

    port = args.port or find_port()
    ser  = open_serial(port, args.baud) if port else None

    if ser:
        print(f'  Port: {port} @ {args.baud}')
        print('  For "add": board must be in DB BUILD mode')
        print('  (hold SW1 within 3 s of "[INIT] Done.")\n')
    else:
        print('  No serial port — add unavailable (list/delete still work)\n')

    entries  = load_header(HEADER_PATH)
    modified = False

    try:
        while True:
            print()
            print('━━━ VoxSV DB Manager ━━━━━━━━━━━━━━━━━━━━━━━')
            print(f'  {len(entries)} speaker(s) in DB')
            print_db(entries)
            print()
            print('  a  Add speaker')
            print('  d  Delete speaker')
            print('  s  Save & quit')
            print('  q  Quit without saving')
            print('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')
            cmd = input('  > ').strip().lower()

            if cmd == 'a':
                new = cmd_add(entries, ser)
                if new is not entries:
                    entries, modified = new, True

            elif cmd == 'd':
                new = cmd_delete(entries)
                if new is not entries:
                    entries, modified = new, True

            elif cmd == 's':
                write_header(entries, HEADER_PATH)
                modified = False
                print('  Run: make -j$(nproc)')
                break

            elif cmd == 'q':
                if modified:
                    if input('  Unsaved changes. Quit? [y/N] ').strip().lower() != 'y':
                        continue
                break

    except KeyboardInterrupt:
        print()
        if modified:
            print('  Interrupted — changes not saved.')

    if ser:
        ser.close()


if __name__ == '__main__':
    main()
