/*******************************************************************************
* Copyright (C) 2019-2024 Maxim Integrated Products, Inc., All rights Reserved.
*
* This software is protected by copyright laws of the United States and
* of foreign countries. This material may also be protected by patent laws
* and technology transfer regulations of the United States and of foreign
* countries. This software is furnished under a license agreement and/or a
* nondisclosure agreement and may only be used or reproduced in accordance
* with the terms of those agreements. Dissemination of this information to
* any party or parties not specified in the license agreement and/or
* nondisclosure agreement is expressly prohibited.
*
* The above copyright notice and this permission notice shall be included
* in all copies or substantial portions of the Software.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
* IN NO EVENT SHALL MAXIM INTEGRATED BE LIABLE FOR ANY CLAIM, DAMAGES
* OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
* OTHER DEALINGS IN THE SOFTWARE.
*
* Except as contained in this notice, the name of Maxim Integrated
* Products, Inc. shall not be used except as stated in the Maxim Integrated
* Products, Inc. Branding Policy.
*
* The mere transfer of this software does not imply any licenses
* of trade secrets, proprietary technology, copyrights, patents,
* trademarks, maskwork rights, or any other form of intellectual
* property whatsoever. Maxim Integrated Products, Inc. retains all
* ownership rights.
*******************************************************************************/

// voxsv
// This file was @generated by ai8xize.py --test-dir sdk/Examples/MAX78000/CNN --prefix voxsv --checkpoint-file /tmp/voxsv_stage4_fakepass.rpxIci.pth.tar --board-name FTHR_RevA --config-file networks/sv.yaml --sample-input tests/sample_voxceleb2_sv.npy --overwrite --device MAX78000 --timer 0 --display-checkpoint --verbose --no-version-check

#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <stdio.h>
#include "mxc.h"
#include "cnn.h"
#include "sampledata.h"
#include "sampleoutput.h"

volatile uint32_t cnn_time; // Stopwatch

void fail(void)
{
  printf("\n*** FAIL ***\n\n");
  while (1);
}

// 1-channel 80x128 data input (10240 bytes / 2560 32-bit words):
// CHW 80x128, channel 0
static const uint32_t input_0[] = SAMPLE_INPUT_0;

/*
 * Pre-processing guide for a live microphone pipeline:
 * 1. Capture mono PCM with the same sample rate used during training.
 * 2. Apply the same framing/windowing pipeline used to build VoxCeleb2_SV features.
 * 3. Convert audio to an 80-bin x 128-frame log-mel/filterbank tensor.
 * 4. Apply the same normalization and int8 quantization used during training.
 * 5. Pack the final tensor as CHW 1x80x128 and copy 2560 words into 0x50400000.
 * 6. Replace the SAMPLE_INPUT memcpy below with your computed feature buffer.
 *
 * Notes:
 * - This network expects acoustic features, not raw microphone PCM samples.
 * - Quantization/range mismatches will hurt accuracy even if the CNN runs.
 * - After inference, compare the normalized 64-D embedding with enrolled
 *   speaker embeddings using cosine similarity or dot product.
 */

void load_input(void)
{
  // This function loads the sample data input -- replace with actual data

  memcpy32((uint32_t *) 0x50400000, input_0, 2560);
}

// Expected output of layer 19 (fc_Gemm_8) for voxsv given the sample input (known-answer test)
// Delete this function for production code
static const uint32_t sample_output[] = SAMPLE_OUTPUT;
int check_output(void)
{
  int i;
  uint32_t mask, len;
  volatile uint32_t *addr;
  const uint32_t *ptr = sample_output;

  while ((addr = (volatile uint32_t *) *ptr++) != 0) {
    mask = *ptr++;
    len = *ptr++;
    for (i = 0; i < len; i++)
      if ((*addr++ & mask) != *ptr++) {
        printf("Data mismatch (%d/%d) at address 0x%08x: Expected 0x%08x, read 0x%08x.\n",
               i + 1, len, addr - 1, *(ptr - 1), *(addr - 1) & mask);
        return CNN_FAIL;
      }
  }

  return CNN_OK;
}

#define VOXSV_EMBEDDING_DIM 64

static int32_t ml_data[CNN_NUM_OUTPUTS];
static int8_t voxsv_embedding_q7[VOXSV_EMBEDDING_DIM];

static float voxsv_sqrt(float value)
{
  float x = value;
  int i;

  if (value <= 0.0f)
    return 0.0f;

  if (x < 1.0f)
    x = 1.0f;

  for (i = 0; i < 8; i++)
    x = 0.5f * (x + value / x);

  return x;
}

static int8_t voxsv_clamp_q7(float value)
{
  if (value > 127.0f)
    return 127;
  if (value < -128.0f)
    return -128;
  return (int8_t) (value >= 0.0f ? value + 0.5f : value - 0.5f);
}

static void voxsv_normalize_embedding_q7(const int32_t *packed_src, int8_t *dst)
{
  const int16_t *src = (const int16_t *) packed_src;
  float sum = 0.0f;
  float scale;
  int i;

  for (i = 0; i < VOXSV_EMBEDDING_DIM; i++)
    sum += (float) src[i] * (float) src[i];

  if (sum <= 0.0f) {
    memset(dst, 0, VOXSV_EMBEDDING_DIM);
    return;
  }

  scale = 128.0f / voxsv_sqrt(sum);

  for (i = 0; i < VOXSV_EMBEDDING_DIM; i++)
    dst[i] = voxsv_clamp_q7((float) src[i] * scale);
}

int main(void)
{
  MXC_ICC_Enable(MXC_ICC0); // Enable cache

  // Switch to 100 MHz clock
  MXC_SYS_Clock_Select(MXC_SYS_CLOCK_IPO);
  SystemCoreClockUpdate();

  printf("Waiting...\n");

  // DO NOT DELETE THIS LINE:
  MXC_Delay(SEC(2)); // Let debugger interrupt if needed

  // Enable peripheral, enable CNN interrupt, turn on CNN clock
  // CNN clock: APB (50 MHz) div 1
  cnn_enable(MXC_S_GCR_PCLKDIV_CNNCLKSEL_PCLK, MXC_S_GCR_PCLKDIV_CNNCLKDIV_DIV1);

  printf("\n*** CNN Inference Test voxsv ***\n");

  cnn_init(); // Bring state machine into consistent state
  cnn_load_weights(); // Load kernels
  cnn_load_bias();
  cnn_configure(); // Configure state machine
  load_input(); // Load data input
  cnn_start(); // Start CNN processing

  while (cnn_time == 0)
    MXC_LP_EnterSleepMode(); // Wait for CNN

  if (check_output() != CNN_OK) fail();
  cnn_unload((uint32_t *) ml_data);
  voxsv_normalize_embedding_q7(ml_data, voxsv_embedding_q7);
  printf("Normalized embedding stored in voxsv_embedding_q7 (Q7, 64 dims).\n");

  printf("\n*** PASS ***\n\n");

#ifdef CNN_INFERENCE_TIMER
  printf("Approximate inference time: %u us\n\n", cnn_time);
#endif

  cnn_disable(); // Shut down CNN clock, disable peripheral


  return 0;
}

/*
  SUMMARY OF OPS
  Hardware: 72,220,672 ops (71,811,072 macc; 296,960 comp; 112,640 add; 0 mul; 0 bitwise)
    Layer 0 (stem_Conv_10): 419,840 ops (368,640 macc; 51,200 comp; 0 add; 0 mul; 0 bitwise)
    Layer 1 (gap_stem_pool.pool): 0 ops (0 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 2 (stage1.conv1_Conv_8): 5,939,200 ops (5,898,240 macc; 40,960 comp; 0 add; 0 mul; 0 bitwise)
    Layer 3 (stage1.conv2_Conv_8): 5,898,240 ops (5,898,240 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 4 (stage1.add): 737,280 ops (655,360 macc; 40,960 comp; 40,960 add; 0 mul; 0 bitwise)
    Layer 5 (pool1.pool): 40,960 ops (0 macc; 40,960 comp; 0 add; 0 mul; 0 bitwise)
    Layer 6 (stage2.conv1_Conv_8): 2,969,600 ops (2,949,120 macc; 20,480 comp; 0 add; 0 mul; 0 bitwise)
    Layer 7 (stage2.conv2_Conv_8): 5,898,240 ops (5,898,240 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 8 (stage2.shortcut_Conv_8): 327,680 ops (327,680 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 9 (stage2.add): 696,320 ops (655,360 macc; 20,480 comp; 20,480 add; 0 mul; 0 bitwise)
    Layer 10 (pool2.pool): 20,480 ops (0 macc; 20,480 comp; 0 add; 0 mul; 0 bitwise)
    Layer 11 (stage3.conv1_Conv_8): 2,959,360 ops (2,949,120 macc; 10,240 comp; 0 add; 0 mul; 0 bitwise)
    Layer 12 (stage3.conv2_Conv_8): 5,898,240 ops (5,898,240 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 13 (stage3.shortcut_Conv_8): 327,680 ops (327,680 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 14 (stage3.add): 675,840 ops (655,360 macc; 10,240 comp; 10,240 add; 0 mul; 0 bitwise)
    Layer 15 (stage4.conv1_Conv_8): 11,816,960 ops (11,796,480 macc; 20,480 comp; 0 add; 0 mul; 0 bitwise)
    Layer 16 (stage4.conv2_Conv_8): 23,592,960 ops (23,592,960 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 17 (stage4.shortcut_Conv_8): 1,310,720 ops (1,310,720 macc; 0 comp; 0 add; 0 mul; 0 bitwise)
    Layer 18 (stage4.add): 2,662,400 ops (2,621,440 macc; 20,480 comp; 20,480 add; 0 mul; 0 bitwise)
    Layer 19 (fc_Gemm_8): 28,672 ops (8,192 macc; 0 comp; 20,480 add; 0 mul; 0 bitwise)

  RESOURCE USAGE
  Weight memory: 319,440 bytes out of 442,368 bytes total (72.2%)
  Bias memory:   784 bytes out of 2,048 bytes total (38.3%)
*/

